version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

# version: 2.1

# executors:
#   default:
#     working_directory: ~/rails-engine
#     docker:
#       - image: circleci/ruby:2.5.3
#         environment:
#           BUNDLE_JOBS: 3
#           BUNDLE_PATH: vendor/bundle
#           BUNDLE_RETRY: 3
#           BUNDLER_VERSION: 2.0.1
#           RAILS_ENV: test
#           DB_HOST: 127.0.0.1
#           PG_HOST: 127.0.0.1
#           PGUSER: aidenmendez
#       - image: circleci/postgres:13.1
#         environment:
#           POSTGRES_DB: rails-engine_test
#           POSTGRES_USER: aidenmendez

# commands:
#   configure_bundler:
#     description: Configure bundler
#     steps:
#       - run:
#           name: Configure bundler
#           command: |
#             echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
#             source $BASH_ENV
#             gem install bundler

# jobs:
#   build:
#     executor: default
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - rails-engine-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - rails-engine-
#       - configure_bundler
#       - run:
#           name: Install bundle
#           command: bundle install
#       - run:
#           name: Wait for DB
#           command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
#       - run:
#           name: Setup DB
#           command: bundle exec rails db:create db:schema:load --trace
#       - save_cache:
#           key: rails-engine-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle
#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - ./rails-engine

# workflows:
#   version: 2
#   integration:
#     jobs:
#       - build